name: Leaders4Leaders
favicon: null
layout_spectrum: 0.76543
typography_spectrum: 0.72881
title: Leaders4Leaders
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69370431-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11153f'
    - '#9ec7b6'
    - '#000040'
    - '#aaaaaa'
    - '#36445c'
  brandStrength: 0.5
  lightness: 0.0008947672322392464
  saturation: 0.6875
  rhythmicContrast: 0.25967097328975797
purpose: []
