name: null
favicon: null
layout_spectrum: 0.7553491934668273
typography_spectrum: 0.7591723406221718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.08668774552643299
  lightness: 0.0008947672322392464
  saturation: 0.6383131206966937
  rhythmicContrast: 0.25967097328975797
purpose: []
